# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_in.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema_in.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fschema_in.proto\"`\n\x07PSquare\x12\r\n\x05value\x18\x01 \x03(\x05\x12&\n\tneighbour\x18\x02 \x03(\x0e\x32\x13.PSquare.Directions\"\x1e\n\nDirections\x12\x06\n\x02Up\x10\x00\x12\x08\n\x04Left\x10\x01\"#\n\x07PPuzzle\x12\x18\n\x06square\x18\x01 \x03(\x0b\x32\x08.PSquare\"%\n\x08PPuzzles\x12\x19\n\x07puzzles\x18\x01 \x03(\x0b\x32\x08.PPuzzleb\x06proto3')
)



_PSQUARE_DIRECTIONS = _descriptor.EnumDescriptor(
  name='Directions',
  full_name='PSquare.Directions',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Up', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Left', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=85,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_PSQUARE_DIRECTIONS)


_PSQUARE = _descriptor.Descriptor(
  name='PSquare',
  full_name='PSquare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PSquare.value', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbour', full_name='PSquare.neighbour', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PSQUARE_DIRECTIONS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=115,
)


_PPUZZLE = _descriptor.Descriptor(
  name='PPuzzle',
  full_name='PPuzzle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='square', full_name='PPuzzle.square', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=152,
)


_PPUZZLES = _descriptor.Descriptor(
  name='PPuzzles',
  full_name='PPuzzles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='puzzles', full_name='PPuzzles.puzzles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=191,
)

_PSQUARE.fields_by_name['neighbour'].enum_type = _PSQUARE_DIRECTIONS
_PSQUARE_DIRECTIONS.containing_type = _PSQUARE
_PPUZZLE.fields_by_name['square'].message_type = _PSQUARE
_PPUZZLES.fields_by_name['puzzles'].message_type = _PPUZZLE
DESCRIPTOR.message_types_by_name['PSquare'] = _PSQUARE
DESCRIPTOR.message_types_by_name['PPuzzle'] = _PPUZZLE
DESCRIPTOR.message_types_by_name['PPuzzles'] = _PPUZZLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PSquare = _reflection.GeneratedProtocolMessageType('PSquare', (_message.Message,), {
  'DESCRIPTOR' : _PSQUARE,
  '__module__' : 'schema_in_pb2'
  # @@protoc_insertion_point(class_scope:PSquare)
  })
_sym_db.RegisterMessage(PSquare)

PPuzzle = _reflection.GeneratedProtocolMessageType('PPuzzle', (_message.Message,), {
  'DESCRIPTOR' : _PPUZZLE,
  '__module__' : 'schema_in_pb2'
  # @@protoc_insertion_point(class_scope:PPuzzle)
  })
_sym_db.RegisterMessage(PPuzzle)

PPuzzles = _reflection.GeneratedProtocolMessageType('PPuzzles', (_message.Message,), {
  'DESCRIPTOR' : _PPUZZLES,
  '__module__' : 'schema_in_pb2'
  # @@protoc_insertion_point(class_scope:PPuzzles)
  })
_sym_db.RegisterMessage(PPuzzles)


# @@protoc_insertion_point(module_scope)
