// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema_in.proto

public final class SchemaIn {
  private SchemaIn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PSquareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PSquare)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool x = 1;</code>
     */
    boolean getX();

    /**
     * <code>bool y = 6;</code>
     */
    boolean getY();
  }
  /**
   * Protobuf type {@code PSquare}
   */
  public  static final class PSquare extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PSquare)
      PSquareOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PSquare.newBuilder() to construct.
    private PSquare(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PSquare() {
      x_ = false;
      y_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PSquare(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              x_ = input.readBool();
              break;
            }
            case 48: {

              y_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchemaIn.internal_static_PSquare_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchemaIn.internal_static_PSquare_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchemaIn.PSquare.class, SchemaIn.PSquare.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private boolean x_;
    /**
     * <code>bool x = 1;</code>
     */
    public boolean getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 6;
    private boolean y_;
    /**
     * <code>bool y = 6;</code>
     */
    public boolean getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != false) {
        output.writeBool(1, x_);
      }
      if (y_ != false) {
        output.writeBool(6, y_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, x_);
      }
      if (y_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchemaIn.PSquare)) {
        return super.equals(obj);
      }
      SchemaIn.PSquare other = (SchemaIn.PSquare) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchemaIn.PSquare parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PSquare parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PSquare parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PSquare parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PSquare parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PSquare parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PSquare parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PSquare parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PSquare parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchemaIn.PSquare parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PSquare parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PSquare parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchemaIn.PSquare prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PSquare}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PSquare)
        SchemaIn.PSquareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchemaIn.internal_static_PSquare_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchemaIn.internal_static_PSquare_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchemaIn.PSquare.class, SchemaIn.PSquare.Builder.class);
      }

      // Construct using SchemaIn.PSquare.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = false;

        y_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchemaIn.internal_static_PSquare_descriptor;
      }

      @java.lang.Override
      public SchemaIn.PSquare getDefaultInstanceForType() {
        return SchemaIn.PSquare.getDefaultInstance();
      }

      @java.lang.Override
      public SchemaIn.PSquare build() {
        SchemaIn.PSquare result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchemaIn.PSquare buildPartial() {
        SchemaIn.PSquare result = new SchemaIn.PSquare(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchemaIn.PSquare) {
          return mergeFrom((SchemaIn.PSquare)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchemaIn.PSquare other) {
        if (other == SchemaIn.PSquare.getDefaultInstance()) return this;
        if (other.getX() != false) {
          setX(other.getX());
        }
        if (other.getY() != false) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchemaIn.PSquare parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchemaIn.PSquare) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean x_ ;
      /**
       * <code>bool x = 1;</code>
       */
      public boolean getX() {
        return x_;
      }
      /**
       * <code>bool x = 1;</code>
       */
      public Builder setX(boolean value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = false;
        onChanged();
        return this;
      }

      private boolean y_ ;
      /**
       * <code>bool y = 6;</code>
       */
      public boolean getY() {
        return y_;
      }
      /**
       * <code>bool y = 6;</code>
       */
      public Builder setY(boolean value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool y = 6;</code>
       */
      public Builder clearY() {
        
        y_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PSquare)
    }

    // @@protoc_insertion_point(class_scope:PSquare)
    private static final SchemaIn.PSquare DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchemaIn.PSquare();
    }

    public static SchemaIn.PSquare getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PSquare>
        PARSER = new com.google.protobuf.AbstractParser<PSquare>() {
      @java.lang.Override
      public PSquare parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PSquare(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PSquare> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PSquare> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchemaIn.PSquare getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBoardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBoard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 2;</code>
     */
    int getX();

    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    java.util.List<SchemaIn.PSquare> 
        getSquaresList();
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    SchemaIn.PSquare getSquares(int index);
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    int getSquaresCount();
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    java.util.List<? extends SchemaIn.PSquareOrBuilder> 
        getSquaresOrBuilderList();
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    SchemaIn.PSquareOrBuilder getSquaresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PBoard}
   */
  public  static final class PBoard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PBoard)
      PBoardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBoard.newBuilder() to construct.
    private PBoard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBoard() {
      x_ = 0;
      squares_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBoard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              x_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                squares_ = new java.util.ArrayList<SchemaIn.PSquare>();
                mutable_bitField0_ |= 0x00000002;
              }
              squares_.add(
                  input.readMessage(SchemaIn.PSquare.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          squares_ = java.util.Collections.unmodifiableList(squares_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchemaIn.internal_static_PBoard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchemaIn.internal_static_PBoard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchemaIn.PBoard.class, SchemaIn.PBoard.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 2;
    private int x_;
    /**
     * <code>int32 x = 2;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int SQUARES_FIELD_NUMBER = 3;
    private java.util.List<SchemaIn.PSquare> squares_;
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    public java.util.List<SchemaIn.PSquare> getSquaresList() {
      return squares_;
    }
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    public java.util.List<? extends SchemaIn.PSquareOrBuilder> 
        getSquaresOrBuilderList() {
      return squares_;
    }
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    public int getSquaresCount() {
      return squares_.size();
    }
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    public SchemaIn.PSquare getSquares(int index) {
      return squares_.get(index);
    }
    /**
     * <code>repeated .PSquare squares = 3;</code>
     */
    public SchemaIn.PSquareOrBuilder getSquaresOrBuilder(
        int index) {
      return squares_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(2, x_);
      }
      for (int i = 0; i < squares_.size(); i++) {
        output.writeMessage(3, squares_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, x_);
      }
      for (int i = 0; i < squares_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, squares_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchemaIn.PBoard)) {
        return super.equals(obj);
      }
      SchemaIn.PBoard other = (SchemaIn.PBoard) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && getSquaresList()
          .equals(other.getSquaresList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      if (getSquaresCount() > 0) {
        hash = (37 * hash) + SQUARES_FIELD_NUMBER;
        hash = (53 * hash) + getSquaresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchemaIn.PBoard parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoard parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PBoard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PBoard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchemaIn.PBoard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBoard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBoard)
        SchemaIn.PBoardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchemaIn.internal_static_PBoard_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchemaIn.internal_static_PBoard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchemaIn.PBoard.class, SchemaIn.PBoard.Builder.class);
      }

      // Construct using SchemaIn.PBoard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSquaresFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        if (squaresBuilder_ == null) {
          squares_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          squaresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchemaIn.internal_static_PBoard_descriptor;
      }

      @java.lang.Override
      public SchemaIn.PBoard getDefaultInstanceForType() {
        return SchemaIn.PBoard.getDefaultInstance();
      }

      @java.lang.Override
      public SchemaIn.PBoard build() {
        SchemaIn.PBoard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchemaIn.PBoard buildPartial() {
        SchemaIn.PBoard result = new SchemaIn.PBoard(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.x_ = x_;
        if (squaresBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            squares_ = java.util.Collections.unmodifiableList(squares_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.squares_ = squares_;
        } else {
          result.squares_ = squaresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchemaIn.PBoard) {
          return mergeFrom((SchemaIn.PBoard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchemaIn.PBoard other) {
        if (other == SchemaIn.PBoard.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (squaresBuilder_ == null) {
          if (!other.squares_.isEmpty()) {
            if (squares_.isEmpty()) {
              squares_ = other.squares_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSquaresIsMutable();
              squares_.addAll(other.squares_);
            }
            onChanged();
          }
        } else {
          if (!other.squares_.isEmpty()) {
            if (squaresBuilder_.isEmpty()) {
              squaresBuilder_.dispose();
              squaresBuilder_ = null;
              squares_ = other.squares_;
              bitField0_ = (bitField0_ & ~0x00000002);
              squaresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSquaresFieldBuilder() : null;
            } else {
              squaresBuilder_.addAllMessages(other.squares_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchemaIn.PBoard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchemaIn.PBoard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>int32 x = 2;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 2;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 2;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<SchemaIn.PSquare> squares_ =
        java.util.Collections.emptyList();
      private void ensureSquaresIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          squares_ = new java.util.ArrayList<SchemaIn.PSquare>(squares_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SchemaIn.PSquare, SchemaIn.PSquare.Builder, SchemaIn.PSquareOrBuilder> squaresBuilder_;

      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public java.util.List<SchemaIn.PSquare> getSquaresList() {
        if (squaresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(squares_);
        } else {
          return squaresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public int getSquaresCount() {
        if (squaresBuilder_ == null) {
          return squares_.size();
        } else {
          return squaresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public SchemaIn.PSquare getSquares(int index) {
        if (squaresBuilder_ == null) {
          return squares_.get(index);
        } else {
          return squaresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder setSquares(
          int index, SchemaIn.PSquare value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.set(index, value);
          onChanged();
        } else {
          squaresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder setSquares(
          int index, SchemaIn.PSquare.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.set(index, builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder addSquares(SchemaIn.PSquare value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.add(value);
          onChanged();
        } else {
          squaresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder addSquares(
          int index, SchemaIn.PSquare value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.add(index, value);
          onChanged();
        } else {
          squaresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder addSquares(
          SchemaIn.PSquare.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.add(builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder addSquares(
          int index, SchemaIn.PSquare.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.add(index, builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder addAllSquares(
          java.lang.Iterable<? extends SchemaIn.PSquare> values) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, squares_);
          onChanged();
        } else {
          squaresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder clearSquares() {
        if (squaresBuilder_ == null) {
          squares_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          squaresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public Builder removeSquares(int index) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.remove(index);
          onChanged();
        } else {
          squaresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public SchemaIn.PSquare.Builder getSquaresBuilder(
          int index) {
        return getSquaresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public SchemaIn.PSquareOrBuilder getSquaresOrBuilder(
          int index) {
        if (squaresBuilder_ == null) {
          return squares_.get(index);  } else {
          return squaresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public java.util.List<? extends SchemaIn.PSquareOrBuilder> 
           getSquaresOrBuilderList() {
        if (squaresBuilder_ != null) {
          return squaresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(squares_);
        }
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public SchemaIn.PSquare.Builder addSquaresBuilder() {
        return getSquaresFieldBuilder().addBuilder(
            SchemaIn.PSquare.getDefaultInstance());
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public SchemaIn.PSquare.Builder addSquaresBuilder(
          int index) {
        return getSquaresFieldBuilder().addBuilder(
            index, SchemaIn.PSquare.getDefaultInstance());
      }
      /**
       * <code>repeated .PSquare squares = 3;</code>
       */
      public java.util.List<SchemaIn.PSquare.Builder> 
           getSquaresBuilderList() {
        return getSquaresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SchemaIn.PSquare, SchemaIn.PSquare.Builder, SchemaIn.PSquareOrBuilder> 
          getSquaresFieldBuilder() {
        if (squaresBuilder_ == null) {
          squaresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SchemaIn.PSquare, SchemaIn.PSquare.Builder, SchemaIn.PSquareOrBuilder>(
                  squares_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          squares_ = null;
        }
        return squaresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PBoard)
    }

    // @@protoc_insertion_point(class_scope:PBoard)
    private static final SchemaIn.PBoard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchemaIn.PBoard();
    }

    public static SchemaIn.PBoard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBoard>
        PARSER = new com.google.protobuf.AbstractParser<PBoard>() {
      @java.lang.Override
      public PBoard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBoard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBoard> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBoard> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchemaIn.PBoard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBoardsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBoards)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Title = 4;</code>
     */
    int getTitle();

    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    java.util.List<SchemaIn.PBoard> 
        getBoardsList();
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    SchemaIn.PBoard getBoards(int index);
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    int getBoardsCount();
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    java.util.List<? extends SchemaIn.PBoardOrBuilder> 
        getBoardsOrBuilderList();
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    SchemaIn.PBoardOrBuilder getBoardsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PBoards}
   */
  public  static final class PBoards extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PBoards)
      PBoardsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBoards.newBuilder() to construct.
    private PBoards(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBoards() {
      title_ = 0;
      boards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBoards(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {

              title_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                boards_ = new java.util.ArrayList<SchemaIn.PBoard>();
                mutable_bitField0_ |= 0x00000002;
              }
              boards_.add(
                  input.readMessage(SchemaIn.PBoard.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          boards_ = java.util.Collections.unmodifiableList(boards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchemaIn.internal_static_PBoards_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchemaIn.internal_static_PBoards_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchemaIn.PBoards.class, SchemaIn.PBoards.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 4;
    private int title_;
    /**
     * <code>int32 Title = 4;</code>
     */
    public int getTitle() {
      return title_;
    }

    public static final int BOARDS_FIELD_NUMBER = 5;
    private java.util.List<SchemaIn.PBoard> boards_;
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    public java.util.List<SchemaIn.PBoard> getBoardsList() {
      return boards_;
    }
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    public java.util.List<? extends SchemaIn.PBoardOrBuilder> 
        getBoardsOrBuilderList() {
      return boards_;
    }
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    public int getBoardsCount() {
      return boards_.size();
    }
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    public SchemaIn.PBoard getBoards(int index) {
      return boards_.get(index);
    }
    /**
     * <code>repeated .PBoard boards = 5;</code>
     */
    public SchemaIn.PBoardOrBuilder getBoardsOrBuilder(
        int index) {
      return boards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (title_ != 0) {
        output.writeInt32(4, title_);
      }
      for (int i = 0; i < boards_.size(); i++) {
        output.writeMessage(5, boards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (title_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, title_);
      }
      for (int i = 0; i < boards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, boards_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchemaIn.PBoards)) {
        return super.equals(obj);
      }
      SchemaIn.PBoards other = (SchemaIn.PBoards) obj;

      boolean result = true;
      result = result && (getTitle()
          == other.getTitle());
      result = result && getBoardsList()
          .equals(other.getBoardsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle();
      if (getBoardsCount() > 0) {
        hash = (37 * hash) + BOARDS_FIELD_NUMBER;
        hash = (53 * hash) + getBoardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchemaIn.PBoards parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoards parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoards parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoards parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoards parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchemaIn.PBoards parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchemaIn.PBoards parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoards parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PBoards parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoards parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchemaIn.PBoards parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchemaIn.PBoards parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchemaIn.PBoards prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBoards}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBoards)
        SchemaIn.PBoardsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchemaIn.internal_static_PBoards_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchemaIn.internal_static_PBoards_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchemaIn.PBoards.class, SchemaIn.PBoards.Builder.class);
      }

      // Construct using SchemaIn.PBoards.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBoardsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = 0;

        if (boardsBuilder_ == null) {
          boards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          boardsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchemaIn.internal_static_PBoards_descriptor;
      }

      @java.lang.Override
      public SchemaIn.PBoards getDefaultInstanceForType() {
        return SchemaIn.PBoards.getDefaultInstance();
      }

      @java.lang.Override
      public SchemaIn.PBoards build() {
        SchemaIn.PBoards result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchemaIn.PBoards buildPartial() {
        SchemaIn.PBoards result = new SchemaIn.PBoards(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        if (boardsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            boards_ = java.util.Collections.unmodifiableList(boards_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.boards_ = boards_;
        } else {
          result.boards_ = boardsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchemaIn.PBoards) {
          return mergeFrom((SchemaIn.PBoards)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchemaIn.PBoards other) {
        if (other == SchemaIn.PBoards.getDefaultInstance()) return this;
        if (other.getTitle() != 0) {
          setTitle(other.getTitle());
        }
        if (boardsBuilder_ == null) {
          if (!other.boards_.isEmpty()) {
            if (boards_.isEmpty()) {
              boards_ = other.boards_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBoardsIsMutable();
              boards_.addAll(other.boards_);
            }
            onChanged();
          }
        } else {
          if (!other.boards_.isEmpty()) {
            if (boardsBuilder_.isEmpty()) {
              boardsBuilder_.dispose();
              boardsBuilder_ = null;
              boards_ = other.boards_;
              bitField0_ = (bitField0_ & ~0x00000002);
              boardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBoardsFieldBuilder() : null;
            } else {
              boardsBuilder_.addAllMessages(other.boards_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchemaIn.PBoards parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchemaIn.PBoards) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int title_ ;
      /**
       * <code>int32 Title = 4;</code>
       */
      public int getTitle() {
        return title_;
      }
      /**
       * <code>int32 Title = 4;</code>
       */
      public Builder setTitle(int value) {
        
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Title = 4;</code>
       */
      public Builder clearTitle() {
        
        title_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<SchemaIn.PBoard> boards_ =
        java.util.Collections.emptyList();
      private void ensureBoardsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          boards_ = new java.util.ArrayList<SchemaIn.PBoard>(boards_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SchemaIn.PBoard, SchemaIn.PBoard.Builder, SchemaIn.PBoardOrBuilder> boardsBuilder_;

      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public java.util.List<SchemaIn.PBoard> getBoardsList() {
        if (boardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(boards_);
        } else {
          return boardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public int getBoardsCount() {
        if (boardsBuilder_ == null) {
          return boards_.size();
        } else {
          return boardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public SchemaIn.PBoard getBoards(int index) {
        if (boardsBuilder_ == null) {
          return boards_.get(index);
        } else {
          return boardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder setBoards(
          int index, SchemaIn.PBoard value) {
        if (boardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardsIsMutable();
          boards_.set(index, value);
          onChanged();
        } else {
          boardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder setBoards(
          int index, SchemaIn.PBoard.Builder builderForValue) {
        if (boardsBuilder_ == null) {
          ensureBoardsIsMutable();
          boards_.set(index, builderForValue.build());
          onChanged();
        } else {
          boardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder addBoards(SchemaIn.PBoard value) {
        if (boardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardsIsMutable();
          boards_.add(value);
          onChanged();
        } else {
          boardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder addBoards(
          int index, SchemaIn.PBoard value) {
        if (boardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardsIsMutable();
          boards_.add(index, value);
          onChanged();
        } else {
          boardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder addBoards(
          SchemaIn.PBoard.Builder builderForValue) {
        if (boardsBuilder_ == null) {
          ensureBoardsIsMutable();
          boards_.add(builderForValue.build());
          onChanged();
        } else {
          boardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder addBoards(
          int index, SchemaIn.PBoard.Builder builderForValue) {
        if (boardsBuilder_ == null) {
          ensureBoardsIsMutable();
          boards_.add(index, builderForValue.build());
          onChanged();
        } else {
          boardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder addAllBoards(
          java.lang.Iterable<? extends SchemaIn.PBoard> values) {
        if (boardsBuilder_ == null) {
          ensureBoardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, boards_);
          onChanged();
        } else {
          boardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder clearBoards() {
        if (boardsBuilder_ == null) {
          boards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          boardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public Builder removeBoards(int index) {
        if (boardsBuilder_ == null) {
          ensureBoardsIsMutable();
          boards_.remove(index);
          onChanged();
        } else {
          boardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public SchemaIn.PBoard.Builder getBoardsBuilder(
          int index) {
        return getBoardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public SchemaIn.PBoardOrBuilder getBoardsOrBuilder(
          int index) {
        if (boardsBuilder_ == null) {
          return boards_.get(index);  } else {
          return boardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public java.util.List<? extends SchemaIn.PBoardOrBuilder> 
           getBoardsOrBuilderList() {
        if (boardsBuilder_ != null) {
          return boardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(boards_);
        }
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public SchemaIn.PBoard.Builder addBoardsBuilder() {
        return getBoardsFieldBuilder().addBuilder(
            SchemaIn.PBoard.getDefaultInstance());
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public SchemaIn.PBoard.Builder addBoardsBuilder(
          int index) {
        return getBoardsFieldBuilder().addBuilder(
            index, SchemaIn.PBoard.getDefaultInstance());
      }
      /**
       * <code>repeated .PBoard boards = 5;</code>
       */
      public java.util.List<SchemaIn.PBoard.Builder> 
           getBoardsBuilderList() {
        return getBoardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SchemaIn.PBoard, SchemaIn.PBoard.Builder, SchemaIn.PBoardOrBuilder> 
          getBoardsFieldBuilder() {
        if (boardsBuilder_ == null) {
          boardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SchemaIn.PBoard, SchemaIn.PBoard.Builder, SchemaIn.PBoardOrBuilder>(
                  boards_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          boards_ = null;
        }
        return boardsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PBoards)
    }

    // @@protoc_insertion_point(class_scope:PBoards)
    private static final SchemaIn.PBoards DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchemaIn.PBoards();
    }

    public static SchemaIn.PBoards getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBoards>
        PARSER = new com.google.protobuf.AbstractParser<PBoards>() {
      @java.lang.Override
      public PBoards parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBoards(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBoards> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBoards> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchemaIn.PBoards getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PSquare_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PSquare_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBoard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PBoard_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBoards_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PBoards_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017schema_in.proto\"\037\n\007PSquare\022\t\n\001x\030\001 \001(\010\022" +
      "\t\n\001y\030\006 \001(\010\".\n\006PBoard\022\t\n\001x\030\002 \001(\005\022\031\n\007squar" +
      "es\030\003 \003(\0132\010.PSquare\"1\n\007PBoards\022\r\n\005Title\030\004" +
      " \001(\005\022\027\n\006boards\030\005 \003(\0132\007.PBoardb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PSquare_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PSquare_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PSquare_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_PBoard_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PBoard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PBoard_descriptor,
        new java.lang.String[] { "X", "Squares", });
    internal_static_PBoards_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PBoards_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PBoards_descriptor,
        new java.lang.String[] { "Title", "Boards", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
